### ISSUE TITLE
Circular import ?

### ISSUE THREAD

**Issue by Simon-Free** [braindecode/braindecode#130]
Hello everyone,

I tried to add some new files to braindecode.datautil, and weren't able to load them properly. During the process, I found one error : 
Input : `from braindecode.datautil import *`
Output : 
```
ImportError                               Traceback (most recent call last)
<ipython-input-5-81dbcb36302e> in <module>
----> 1 from braindecode.datautil import *

~/miniconda3/lib/python3.7/site-packages/braindecode/datautil/__init__.py in <module>
      3 """
      4 
----> 5 from .windowers import create_windows_from_events, create_fixed_length_windows
      6 from .preprocess import zscore, scale, exponential_moving_demean, exponential_moving_standardize

~/miniconda3/lib/python3.7/site-packages/braindecode/datautil/windowers.py in <module>
     13 import pandas as pd
     14 
---> 15 from ..datasets.base import WindowsDataset, BaseConcatDataset
     16 
     17 

~/miniconda3/lib/python3.7/site-packages/braindecode/datasets/__init__.py in <module>
      5 from .moabb import MOABBDataset
      6 from .tuh import TUHAbnormal
----> 7 from .mne import create_from_mne_raw, create_from_mne_epochs
      8 from .xy import create_from_X_y

~/miniconda3/lib/python3.7/site-packages/braindecode/datasets/mne.py in <module>
      4 
      5 from .base import BaseDataset, BaseConcatDataset, WindowsDataset
----> 6 from ..datautil.windowers import (
      7     _check_windowing_arguments, create_windows_from_events)
      8 

ImportError: cannot import name '_check_windowing_arguments' from 'braindecode.datautil.windowers' (/home/parietal/sfreybur/miniconda3/lib/python3.7/site-packages/braindecode/datautil/windowers.py)
```

Cause seems to be a circular import, but I am not confident enough to change the code organisation by myself.

**Comment by robintibor** [comment]
Thanks for the info! Can you try moving the imports  

https://github.com/braindecode/braindecode/blob/41a216572f08ef23fd0af47e10e89bc9179cce5e/braindecode/datasets/mne.py#L6-L7

inside the start of these functions (after docstring of course):

https://github.com/braindecode/braindecode/blob/41a216572f08ef23fd0af47e10e89bc9179cce5e/braindecode/datasets/mne.py#L10-L13

https://github.com/braindecode/braindecode/blob/41a216572f08ef23fd0af47e10e89bc9179cce5e/braindecode/datasets/mne.py#L74-L75

atm don't see a better solution, unless we do a bigger restructuring, changing the datautil/datasets structure

**Comment by Simon-Free** [comment]
Done ! Now I have this error
```
>>> from braindecode.datautil import *
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/storage/store/work/sfreybur/braindecode/braindecode/datautil/__init__.py", line 5, in <module>
    from .windowers import create_windows_from_events, create_fixed_length_windows
  File "/storage/store/work/sfreybur/braindecode/braindecode/datautil/windowers.py", line 15, in <module>
    from ..datasets.base import WindowsDataset, BaseConcatDataset
  File "/storage/store/work/sfreybur/braindecode/braindecode/datasets/__init__.py", line 8, in <module>
    from .xy import create_from_X_y
  File "/storage/store/work/sfreybur/braindecode/braindecode/datasets/xy.py", line 7, in <module>
    from ..datautil.windowers import (
ImportError: cannot import name 'create_fixed_length_windows' from 'braindecode.datautil.windowers' (/storage/store/work/sfreybur/braindecode/braindecode/datautil/windowers.py)
```

**Comment by robintibor** [comment]
ok I guess we may need to do a little bit more about it :( what are your thoughts @sliwy @agramfort  is it still recommendable to do some bigger restructuring or how would you deal with this? 

For now, @Simon-Free  you could also move the imports inside windowers.py, so inside https://github.com/braindecode/braindecode/blob/41a216572f08ef23fd0af47e10e89bc9179cce5e/braindecode/datautil/windowers.py#L18-L22
https://github.com/braindecode/braindecode/blob/41a216572f08ef23fd0af47e10e89bc9179cce5e/braindecode/datautil/windowers.py#L154-L158

**Comment by Simon-Free** [comment]
Ok now it works ! I'll add some TODOs, PR it, and will think about a nice way to fix it.

**Comment by agramfort** [comment]
send us a PR !

>

**Comment by sliwy** [comment]
i took a quick look at this issue earlier but now I finished a PR #131 . @Simon-Free Can you check if this fix the problem? I can now execute the statement you mentioned.

@robintibor do you feel that moving those files is ok and consistent with the package architecture?

**Comment by robintibor** [comment]
solved by #131

**Comment by sepahsaalaar93** [comment]
Hi @robintibor
I have the same problem and same errors when trying to import "create_from_X_y" by this command:
`from braindecode.datautil import create_from_X_y`
After moving imports in above mentioned "mne.py" and " windowers.py" I still can't import "create_from_X_y" and I got this error:
"Traceback (most recent call last):

  File "<ipython-input-1-94a865e0cc4c>", line 1, in <module>
    from braindecode.datautil import create_from_X_y

ImportError: cannot import name 'create_from_X_y' from 'braindecode.datautil' (D:\anaconda3\envs\torch\lib\site-packages\braindecode\datautil\__init__.py)"

**Comment by matthieutrs** [comment]
I did face a similar issue that seems to happen when incompatible packages are installed simultaneously (in my case, I tried using torch 2.0). 
Using torch versions < 2.0 and `pip install moabb` + `pip install braindecode` solved it for me.

To reproduce the issue: create a new env and
```
pip install torch torchvision torchaudio   # downloads torch 2.0
pip install git+https://github.com/NeuroTechX/moabb@develop  # downloads the develop (default branch) of moabb
pip install braindecode
```

This yields:
```
python3
>>> import braindecode
>>> from braindecode.datasets import MOABBDataset
...
ImportError: cannot import name 'create_from_X_y' from partially initialized module 'braindecode.datasets' (most likely due to a circular import)
```

**Comment by bruAristimunha** [comment]
Hey, @matthieutrs!

I think this error comes from the moabb side, given that they (me!) add an optional dependency in braindecode. I'll try to solve it for you. Does the error persist if you change the installation order?

**Comment by bruAristimunha** [comment]
Okay, thank you so much for your input!

FYI, @sylvchev.

**Comment by bruAristimunha** [comment]
a temporary solution: reduce the version of your numpy.

In the meantime, I will correct the moabb.

**Comment by bruAristimunha** [comment]
Solved @matthieutrs!

**Comment by matthieutrs** [comment]
Hey @bruAristimunha, I've checked and your update does fix the issue on my side. Thanks a lot!!
